import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/Colors';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginVertical: 10,
    marginHorizontal: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  eliteBadge: {
    backgroundColor: '#fef3c7',
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  eliteText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#a38119',
    marginLeft: 4,
    marginRight: 4,
  },
  imageContainer: {
    height: 200,
    position: 'relative',
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    backgroundColor: '#38bdf8',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    alignItems: 'center',
  },
  verifiedText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 4,
    marginRight: 4,
  },
  image: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.gray,
  },
  favButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 20,
    padding: 6,
  },
  details: {
    padding: 12,
  },
  price: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ef4444',
    marginBottom: 4,
  },
  title: {
    fontSize: 15,
    color: Colors.black,
    marginBottom: 8,
    lineHeight: 20,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    marginLeft: 12,
  },
  infoText: {
    fontSize: 13,
    color: Colors.mediumGray,
    marginLeft: 4,
    marginRight: 4,
  },
  address: {
    fontSize: 13,
    color: Colors.mediumGray,
    marginBottom: 2,
  },
  time: {
    fontSize: 12,
    color: Colors.mediumGray,
    marginBottom: 12,
  },
  actions: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 12,
  },
  whatsappButton: {
    flex: 1,
    height: 44,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#25D366',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    marginLeft: 8,
  },
  callButton: {
    flex: 3,
    height: 44,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Colors.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  callText: {
    color: Colors.primary,
    fontWeight: '600',
    marginLeft: 8,
    marginRight: 8,
  },
});
